---
- name: Resource Group Creation.
  hosts: localhost
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml

    - name: Create resource Group
      ibm_resource_group:
        name: "{{ resource_group_name }}"
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
      register: rg_create_output
      
    - name: Save newly created resource group info as fact
      set_fact:
        cacheable: True
        resource_group: "{{ rg_create_output.resource }}"
      when: rg_create_output.resource.id is defined

    - name: Print Resource group info 
      debug:
        msg: "Resource Group : {{ resource_group }}"

        

      
